/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 src/assets/Soldier.glb -o src/components/Soldier.jsx -r public 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import SoldierUrl from "../assets/Soldier.glb";
import { usePlayerStore } from "../store/playerStore";
import { socket } from "./SocketManager";
import { useFrame } from "@react-three/fiber";

export const Soldiers = () => {
  const soldiers = usePlayerStore((state) => state.players);
  return soldiers
    .filter((soldier) => soldier.id !== socket.id)
    .map((coords, index) => {
      return (
        <Soldier
          key={index}
          rotation={[0, coords.rotation, 0]}
          position={[
            coords.position.x,
            coords.position.y - 1,
            coords.position.z,
          ]}
        />
      );
    });
};

export function Soldier(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(SoldierUrl);
  const [animation, setAnimation] = useState("CharacterArmature|Idle");

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation]?.fadeOut(0.5);
  }, [animation]);

  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group
            name="Soldier_Body"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Soldier_Body_1"
              geometry={nodes.Soldier_Body_1.geometry}
              material={materials.Black}
              skeleton={nodes.Soldier_Body_1.skeleton}
            />
            <skinnedMesh
              name="Soldier_Body_2"
              geometry={nodes.Soldier_Body_2.geometry}
              material={materials.Swat}
              skeleton={nodes.Soldier_Body_2.skeleton}
            />
            <skinnedMesh
              name="Soldier_Body_3"
              geometry={nodes.Soldier_Body_3.geometry}
              material={materials.Skin}
              skeleton={nodes.Soldier_Body_3.skeleton}
            />
          </group>
          <group
            name="Soldier_Feet"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Soldier_Feet_1"
              geometry={nodes.Soldier_Feet_1.geometry}
              material={materials.Black}
              skeleton={nodes.Soldier_Feet_1.skeleton}
            />
            <skinnedMesh
              name="Soldier_Feet_2"
              geometry={nodes.Soldier_Feet_2.geometry}
              material={materials.Grey}
              skeleton={nodes.Soldier_Feet_2.skeleton}
            />
          </group>
          <group
            name="Soldier_Head"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Soldier_Head_1"
              geometry={nodes.Soldier_Head_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Soldier_Head_1.skeleton}
            />
            <skinnedMesh
              name="Soldier_Head_2"
              geometry={nodes.Soldier_Head_2.geometry}
              material={materials.Hair_Brown}
              skeleton={nodes.Soldier_Head_2.skeleton}
            />
            <skinnedMesh
              name="Soldier_Head_3"
              geometry={nodes.Soldier_Head_3.geometry}
              material={materials.Brown}
              skeleton={nodes.Soldier_Head_3.skeleton}
            />
          </group>
          <group
            name="Soldier_Legs"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Soldier_Legs_1"
              geometry={nodes.Soldier_Legs_1.geometry}
              material={materials.Black}
              skeleton={nodes.Soldier_Legs_1.skeleton}
            />
            <skinnedMesh
              name="Soldier_Legs_2"
              geometry={nodes.Soldier_Legs_2.geometry}
              material={materials.Swat}
              skeleton={nodes.Soldier_Legs_2.skeleton}
            />
            <skinnedMesh
              name="Soldier_Legs_3"
              geometry={nodes.Soldier_Legs_3.geometry}
              material={materials.Grey}
              skeleton={nodes.Soldier_Legs_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(SoldierUrl);
